# Generated by Django 4.2.3 on 2023-07-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='I have no bio', max_length=250),
        ),
    ]
